from power_supply_communication_functions import *

print(request_data_from_address(uart_link,5005))
print(request_data_from_address(uart_link,5006))
print(request_data_from_address(uart_link,5007))
print(request_data_from_address(uart_link,5008))
print(request_data_from_address(uart_link,5009))
print(request_data_from_address(uart_link,5010))
print(request_data_from_address(uart_link,5011))
print(request_data_from_address(uart_link,5012))
print(request_data_from_address(uart_link,5013))
print(request_data_from_address(uart_link,5014))
print(request_data_from_address(uart_link,5015))
print(request_data_from_address(uart_link,5016))
print(request_data_from_address(uart_link,5017))
print(request_data_from_address(uart_link,5018))
print(request_data_from_address(uart_link,5019))
print(request_data_from_address(uart_link,5020))
