-- main_clock.vhd

-- Generated using ACDS version 25.1 129

library IEEE;
library altera_iopll_2000;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity main_clock is
	port (
		refclk   : in  std_logic := '0'; --  refclk.clk,   The reference clock source that drives the I/O PLL.
		rst      : in  std_logic := '0'; --   reset.reset, The asynchronous reset port for the output clocks. Drive this port high to reset all output clocks to the value of 0.
		outclk_0 : out std_logic         -- outclk0.clk,   Output clock Channel 0 from I/O PLL.
	);
end entity main_clock;

architecture rtl of main_clock is
	component main_clock_altera_iopll_2000_jajozcy_cmp is
		port (
			refclk   : in  std_logic := 'X'; -- clk
			rst      : in  std_logic := 'X'; -- reset
			outclk_0 : out std_logic         -- clk
		);
	end component main_clock_altera_iopll_2000_jajozcy_cmp;

	for iopll_0 : main_clock_altera_iopll_2000_jajozcy_cmp
		use entity altera_iopll_2000.main_clock_altera_iopll_2000_jajozcy;
begin

	iopll_0 : component main_clock_altera_iopll_2000_jajozcy_cmp
		port map (
			refclk   => refclk,   --  refclk.clk
			rst      => rst,      --   reset.reset
			outclk_0 => outclk_0  -- outclk0.clk
		);

end architecture rtl; -- of main_clock
